module.exports = {
  arrowParens: 'always',
  bracketSameLine: true,
  bracketSpacing: true,
  jsxSingleQuote: true,
  useTabs: false,
  tabWidth: 2,
  printWidth: 80,
  proseWrap: 'preserve',
  quoteProps: 'preserve',
  semi: true,
  singleAttributePerLine: true,
  singleQuote: true,
  trailingComma: 'all',
  embeddedLanguageFormatting: 'auto',
  htmlWhitespaceSensitivity: 'css',
  rangeStart: 5,
  plugins: [require('prettier-plugin-tailwindcss')],
};
